/**
 * PDF Service
 * Generates PDF reports for cases
 */

import * as FileSystem from 'expo-file-system/legacy';
import * as Sharing from 'expo-sharing';
import { Alert } from 'react-native';

interface CaseReportData {
  reportId?: string;
  caseNumber: string;
  generatedAt: string;
  summary: any;
  timeline: any[];
  actions: any;
  financial: any;
  intelligence: any;
  performance: any;
  aiFeedback: any;
  recommendations: string[];
}

/**
 * Generate PDF from case report data
 * Note: This is a simplified version. For production, use react-native-pdf or expo-print
 */
export async function generatePDF(
  reportData: CaseReportData,
  caseId: string
): Promise<string> {
  try {
    // Create a simple text-based report (in production, use proper PDF library)
    const reportContent = `
AEGIS Case Report
==================

Case Number: ${reportData.caseNumber}
Generated At: ${new Date(reportData.generatedAt).toLocaleString()}

Summary:
--------
Fraud Type: ${reportData.summary.fraudType}
Amount Lost: ₹${reportData.summary.amount?.toLocaleString() || '0'}
Status: ${reportData.summary.status}
Recovery Rate: ${reportData.financial?.recoveryRate || 0}%

Financial Details:
-----------------
Amount Lost: ₹${reportData.financial?.amountLost?.toLocaleString() || '0'}
Amount Recovered: ₹${reportData.financial?.amountRecovered?.toLocaleString() || '0'}
Accounts Frozen: ${reportData.financial?.accountsFrozen || 0}

Performance Metrics:
-------------------
Freeze Time: ${reportData.performance?.freezeTime || 'N/A'}
Prediction Accuracy: ${reportData.aiFeedback?.predictionAccuracy || 'N/A'}
Total Response Time: ${reportData.performance?.totalResponseTime || 'N/A'}

Recommendations:
---------------
${reportData.recommendations?.map((r, i) => `${i + 1}. ${r}`).join('\n') || 'None'}

---
Generated by AEGIS CST-Transformer
`;

    // Save to file system
    const fileName = `AEGIS_Report_${caseId}_${Date.now()}.txt`;
    const fileUri = `${FileSystem.documentDirectory}${fileName}`;
    
    // Write file - expo-file-system handles encoding automatically
    // If encoding parameter is needed, it's handled by the library
    await FileSystem.writeAsStringAsync(fileUri, reportContent);

    // In production, convert to PDF using react-native-pdf or expo-print
    // For now, return the text file URI
    return fileUri;
  } catch (error: any) {
    console.error('Error generating PDF:', error);
    throw new Error('Failed to generate PDF report');
  }
}

/**
 * Export case report as PDF
 */
export async function exportCaseReportPDF(
  caseId: string,
  reportData: CaseReportData
): Promise<{ success: boolean; uri?: string; error?: string }> {
  try {
    const pdfUri = await generatePDF(reportData, caseId);
    
    // Check if sharing is available
    const isAvailable = await Sharing.isAvailableAsync();
    if (isAvailable) {
      await Sharing.shareAsync(pdfUri);
      return { success: true, uri: pdfUri };
    } else {
      Alert.alert('Success', `Report saved to: ${pdfUri}`);
      return { success: true, uri: pdfUri };
    }
  } catch (error: any) {
    return { success: false, error: error.message || 'Failed to export PDF' };
  }
}

