import React from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  Share,
  Alert,
} from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { Ionicons } from '@expo/vector-icons';
import { useRoute, useNavigation } from '@react-navigation/native';
import { useTheme } from '../theme/theme';
import { generateCaseReport } from '../services/reportService';

export default function CaseReportScreen() {
  const { theme } = useTheme();
  const route = useRoute();
  const navigation = useNavigation();
  const { caseId } = route.params as any || {};

  const formatCurrency = (amount: number | undefined | null) => {
    if (!amount || isNaN(amount)) {
      return '₹0';
    }
    if (amount >= 100000) {
      return `₹${(amount / 100000).toFixed(1)}L`;
    }
    return `₹${amount.toLocaleString()}`;
  };

  const handleShare = async () => {
    try {
      await Share.share({
        message: `AEGIS Case Report - Case ${caseId || '#MH-2025-84721'}`,
        title: 'Case Report',
      });
    } catch (error) {
      console.error('Error sharing:', error);
    }
  };

  const handleDownload = async () => {
    try {
      if (caseId) {
        const result = await generateCaseReport(caseId);
        if (result.success) {
          // Generate PDF using pdfService
          try {
            const { exportCaseReportPDF } = require('../services/pdfService');
            const pdfResult = await exportCaseReportPDF(caseId, result.data);
            
            if (pdfResult.success) {
              Alert.alert('Success', 'PDF report generated and ready to share');
            } else {
              Alert.alert('Error', pdfResult.error || 'Failed to generate PDF');
            }
          } catch (pdfError: any) {
            console.warn('PDF generation not available:', pdfError);
            // Fallback: just show success message
            Alert.alert('Success', 'Report data generated. PDF export requires additional setup.');
          }
        } else {
          Alert.alert('Error', result.error || 'Failed to generate PDF');
        }
      } else {
        Alert.alert('Error', 'Case ID is missing');
      }
    } catch (error: any) {
      console.error('Error downloading report:', error);
      Alert.alert('Error', 'Failed to generate PDF report');
    }
  };

  return (
    <View style={[styles.container, { backgroundColor: '#f8fafc' }]}>
      {/* Header */}
      <LinearGradient
        colors={['#2563eb', '#4f46e5', '#7c3aed']}
        style={styles.header}
      >
        <View style={styles.headerContent}>
          <TouchableOpacity
            style={styles.backButton}
            onPress={() => navigation.goBack()}
            activeOpacity={0.7}
          >
            <Ionicons name="arrow-back" size={24} color="#FFFFFF" />
          </TouchableOpacity>
          <View style={styles.headerText}>
            <Text style={styles.headerTitle}>AI Case Report</Text>
            <Text style={styles.headerSubtitle}>Case {caseId || '#MH-2025-84721'}</Text>
          </View>
          <TouchableOpacity
            style={styles.iconButton}
            onPress={handleShare}
            activeOpacity={0.7}
          >
            <Ionicons name="share" size={20} color="#FFFFFF" />
          </TouchableOpacity>
          <TouchableOpacity
            style={styles.iconButton}
            onPress={handleDownload}
            activeOpacity={0.7}
          >
            <Ionicons name="download" size={20} color="#FFFFFF" />
          </TouchableOpacity>
        </View>

        {/* AI Badge */}
        <View style={styles.aiBadge}>
          <LinearGradient
            colors={['#06b6d4', '#3b82f6']}
            style={styles.aiBadgeGradient}
          >
            <Ionicons name="bulb" size={16} color="#FFFFFF" />
          </LinearGradient>
          <View>
            <Text style={styles.aiBadgeTitle}>AI-Powered Analysis</Text>
            <Text style={styles.aiBadgeSubtitle}>Generated by AEGIS CST-Transformer</Text>
          </View>
        </View>
      </LinearGradient>

      <ScrollView
        style={styles.scrollView}
        contentContainerStyle={styles.scrollContent}
        showsVerticalScrollIndicator={false}
      >
        {/* Case Summary */}
        <View style={[styles.card, { backgroundColor: '#FFFFFF' }]}>
          <View style={styles.cardHeader}>
            <Ionicons name="checkmark-circle" size={24} color="#22c55e" />
            <Text style={styles.cardTitle}>Case Outcome Summary</Text>
          </View>
          <View style={styles.statsGrid}>
            <View style={[styles.statBox, { backgroundColor: '#dcfce7' }]}>
              <Text style={[styles.statValue, { color: '#22c55e' }]}>₹3.1L</Text>
              <Text style={styles.statLabel}>Recovered</Text>
            </View>
            <View style={[styles.statBox, { backgroundColor: '#dbeafe' }]}>
              <Text style={[styles.statValue, { color: '#3b82f6' }]}>88.6%</Text>
              <Text style={styles.statLabel}>Recovery Rate</Text>
            </View>
          </View>
          <View style={styles.summaryRow}>
            <Text style={styles.summaryLabel}>Total Fraud Amount</Text>
            <Text style={styles.summaryValue}>{formatCurrency(350000)}</Text>
          </View>
          <View style={styles.summaryRow}>
            <Text style={styles.summaryLabel}>Amount Recovered</Text>
            <Text style={[styles.summaryValue, { color: '#22c55e' }]}>{formatCurrency(310000)}</Text>
          </View>
          <View style={styles.summaryRow}>
            <Text style={styles.summaryLabel}>Time to Resolution</Text>
            <Text style={styles.summaryValue}>23 minutes</Text>
          </View>
          <View style={styles.summaryRow}>
            <Text style={styles.summaryLabel}>Mule Accounts Frozen</Text>
            <Text style={styles.summaryValue}>4 accounts</Text>
          </View>
          <View style={styles.summaryRow}>
            <Text style={styles.summaryLabel}>Suspects Apprehended</Text>
            <Text style={styles.summaryValue}>1 person</Text>
          </View>
        </View>

        {/* Timeline */}
        <View style={[styles.card, { backgroundColor: '#FFFFFF' }]}>
          <Text style={styles.cardTitle}>Timeline</Text>
          <View style={styles.timeline}>
            <View style={styles.timelineItem}>
              <View style={[styles.timelineDot, { backgroundColor: '#22c55e' }]} />
              <View style={styles.timelineContent}>
                <Text style={styles.timelineTime}>14:23</Text>
                <Text style={styles.timelineEvent}>Fraud detected</Text>
              </View>
            </View>
            <View style={styles.timelineItem}>
              <View style={[styles.timelineDot, { backgroundColor: '#3b82f6' }]} />
              <View style={styles.timelineContent}>
                <Text style={styles.timelineTime}>14:25</Text>
                <Text style={styles.timelineEvent}>AI prediction generated</Text>
              </View>
            </View>
            <View style={styles.timelineItem}>
              <View style={[styles.timelineDot, { backgroundColor: '#f59e0b' }]} />
              <View style={styles.timelineContent}>
                <Text style={styles.timelineTime}>14:28</Text>
                <Text style={styles.timelineEvent}>Accounts frozen via NPCI</Text>
              </View>
            </View>
            <View style={styles.timelineItem}>
              <View style={[styles.timelineDot, { backgroundColor: '#8b5cf6' }]} />
              <View style={styles.timelineContent}>
                <Text style={styles.timelineTime}>14:35</Text>
                <Text style={styles.timelineEvent}>Teams deployed</Text>
              </View>
            </View>
            <View style={styles.timelineItem}>
              <View style={[styles.timelineDot, { backgroundColor: '#22c55e' }]} />
              <View style={styles.timelineContent}>
                <Text style={styles.timelineTime}>14:46</Text>
                <Text style={styles.timelineEvent}>Case resolved</Text>
              </View>
            </View>
          </View>
        </View>

        {/* AI Insights */}
        <View style={[styles.card, { backgroundColor: '#FFFFFF' }]}>
          <Text style={styles.cardTitle}>AI Insights</Text>
          <View style={styles.insightBox}>
            <Ionicons name="bulb" size={20} color="#3b82f6" />
            <Text style={styles.insightText}>
              Prediction accuracy: 94%. Model correctly identified HDFC ATM Lokhandwala as the withdrawal location based on historical patterns and distance analysis.
            </Text>
          </View>
          <View style={styles.insightBox}>
            <Ionicons name="warning" size={20} color="#f59e0b" />
            <Text style={styles.insightText}>
              Mule network detected: 2 of 3 accounts linked to known fraud ring "Western Mumbai Ring". Recommend deeper investigation.
            </Text>
          </View>
        </View>

        {/* AI Prediction Accuracy - Matching MVP */}
        <View style={[styles.card, { backgroundColor: '#FFFFFF', borderWidth: 2, borderColor: '#3b82f6' }]}>
          <View style={styles.cardHeader}>
            <Ionicons name="locate" size={24} color="#9333ea" />
            <Text style={styles.cardTitle}>AI Prediction Accuracy</Text>
          </View>
          
          <View style={[styles.successBanner, { backgroundColor: '#dcfce7', borderColor: '#bbf7d0' }]}>
            <View style={styles.successBannerContent}>
              <View style={[styles.successIcon, { backgroundColor: '#22c55e' }]}>
                <Text style={styles.successCheck}>✓</Text>
              </View>
              <View>
                <Text style={styles.successTitle}>Exact Location Match!</Text>
                <Text style={styles.successSubtitle}>Suspect arrested at predicted ATM</Text>
              </View>
            </View>
          </View>
          
          <View style={styles.accuracyMetrics}>
            <View style={styles.accuracyMetric}>
              <View style={styles.accuracyHeader}>
                <Text style={styles.accuracyLabel}>Location Accuracy</Text>
                <Text style={[styles.accuracyValue, { color: '#22c55e' }]}>100%</Text>
              </View>
              <View style={styles.progressBar}>
                <View style={[styles.progressFill, { width: '100%', backgroundColor: '#22c55e' }]} />
              </View>
            </View>
            <View style={styles.accuracyMetric}>
              <View style={styles.accuracyHeader}>
                <Text style={styles.accuracyLabel}>Time Window Accuracy</Text>
                <Text style={[styles.accuracyValue, { color: '#22c55e' }]}>92%</Text>
              </View>
              <View style={styles.progressBar}>
                <View style={[styles.progressFill, { width: '92%', backgroundColor: '#22c55e' }]} />
              </View>
            </View>
            <View style={styles.accuracyMetric}>
              <View style={styles.accuracyHeader}>
                <Text style={styles.accuracyLabel}>Mule Detection Accuracy</Text>
                <Text style={[styles.accuracyValue, { color: '#3b82f6' }]}>87%</Text>
              </View>
              <View style={styles.progressBar}>
                <View style={[styles.progressFill, { width: '87%', backgroundColor: '#3b82f6' }]} />
              </View>
            </View>
          </View>
        </View>

        {/* How AI Solved This Case - Matching MVP */}
        <View style={[styles.card, { backgroundColor: '#FFFFFF' }]}>
          <View style={styles.cardHeader}>
            <Ionicons name="bulb" size={24} color="#4f46e5" />
            <Text style={styles.cardTitle}>How AI Solved This Case</Text>
          </View>
          
          <View style={styles.aiTimeline}>
            <View style={styles.timelineLine} />
            
            <View style={styles.aiStep}>
              <View style={[styles.aiStepDot, { backgroundColor: '#3b82f6' }]} />
              <View style={[styles.aiStepCard, { backgroundColor: '#dbeafe', borderColor: '#bfdbfe' }]}>
                <Text style={[styles.aiStepLabel, { color: '#1e40af' }]}>STEP 1 • Complaint Analysis</Text>
                <Text style={styles.aiStepText}>Extracted victim details, transaction IDs, and fraud type (OTP scam)</Text>
                <Text style={styles.aiStepTime}>Time: 2.3 seconds</Text>
              </View>
            </View>
            
            <View style={styles.aiStep}>
              <View style={[styles.aiStepDot, { backgroundColor: '#6366f1' }]} />
              <View style={[styles.aiStepCard, { backgroundColor: '#eef2ff', borderColor: '#c7d2fe' }]}>
                <Text style={[styles.aiStepLabel, { color: '#4338ca' }]}>STEP 2 • Money Trail Tracing</Text>
                <Text style={styles.aiStepText}>Mapped ₹3.5L through 4 mule accounts across 3 banks</Text>
                <View style={styles.bankFlow}>
                  <Text style={styles.bankFlowText}>SBI → HDFC → ICICI → Axis</Text>
                </View>
                <Text style={styles.aiStepTime}>Time: 8.7 seconds</Text>
              </View>
            </View>
            
            <View style={styles.aiStep}>
              <View style={[styles.aiStepDot, { backgroundColor: '#9333ea' }]} />
              <View style={[styles.aiStepCard, { backgroundColor: '#faf5ff', borderColor: '#e9d5ff' }]}>
                <Text style={[styles.aiStepLabel, { color: '#7e22ce' }]}>STEP 3 • Mule Network Detection</Text>
                <Text style={styles.aiStepText}>Identified 4 accounts as part of known fraud network</Text>
                <View style={styles.aiStepDetails}>
                  <Text style={styles.aiStepDetailText}>• Account ages: All {'<'} 6 months</Text>
                  <Text style={styles.aiStepDetailText}>• Similar KYC patterns detected</Text>
                  <Text style={styles.aiStepDetailText}>• Linked to 12 previous cases</Text>
                </View>
                <Text style={styles.aiStepTime}>Time: 5.2 seconds</Text>
              </View>
            </View>
            
            <View style={styles.aiStep}>
              <View style={[styles.aiStepDot, { backgroundColor: '#f97316' }]} />
              <View style={[styles.aiStepCard, { backgroundColor: '#fff7ed', borderColor: '#fed7aa' }]}>
                <Text style={[styles.aiStepLabel, { color: '#c2410c' }]}>STEP 4 • Location Prediction</Text>
                <Text style={styles.aiStepText}>CST-Transformer predicted HDFC ATM, Lokhandwala</Text>
                <View style={styles.aiStepDetails}>
                  <Text style={styles.aiStepDetailText}>• Based on mule's registered address proximity</Text>
                  <Text style={styles.aiStepDetailText}>• Historical withdrawal patterns</Text>
                  <Text style={styles.aiStepDetailText}>• ATM cash availability</Text>
                </View>
                <Text style={styles.aiStepTime}>Confidence: 94%</Text>
              </View>
            </View>
            
            <View style={styles.aiStep}>
              <View style={[styles.aiStepDot, { backgroundColor: '#22c55e' }]} />
              <View style={[styles.aiStepCard, { backgroundColor: '#f0fdf4', borderColor: '#bbf7d0' }]}>
                <Text style={[styles.aiStepLabel, { color: '#166534' }]}>STEP 5 • Action Execution</Text>
                <Text style={styles.aiStepText}>Auto-froze 4 accounts + dispatched Team Alpha-7</Text>
                <View style={styles.actionBadges}>
                  <View style={[styles.actionBadge, { backgroundColor: '#dcfce7' }]}>
                    <Text style={[styles.actionBadgeText, { color: '#166534' }]}>Freeze: 47s</Text>
                  </View>
                  <View style={[styles.actionBadge, { backgroundColor: '#dcfce7' }]}>
                    <Text style={[styles.actionBadgeText, { color: '#166534' }]}>Team ETA: 4 min</Text>
                  </View>
                </View>
              </View>
            </View>
          </View>
        </View>

        {/* Key AI Insights - Matching MVP */}
        <LinearGradient
          colors={['#1e293b', '#0f172a']}
          style={styles.insightsCard}
        >
          <View style={styles.insightsHeader}>
            <Ionicons name="sparkles" size={20} color="#06b6d4" />
            <Text style={styles.insightsTitle}>Key AI Insights</Text>
          </View>
          
          <View style={styles.insightItems}>
            <View style={styles.insightItemCard}>
              <Text style={styles.insightEmoji}>🎯</Text>
              <View style={styles.insightItemContent}>
                <Text style={styles.insightItemTitle}>Why This Location?</Text>
                <Text style={styles.insightItemText}>
                  Primary mule's KYC address is 1.2 km from this ATM. Historical data shows 73% of mules withdraw within 2 km of registered address.
                </Text>
              </View>
            </View>
            
            <View style={styles.insightItemCard}>
              <Text style={styles.insightEmoji}>⏱️</Text>
              <View style={styles.insightItemContent}>
                <Text style={styles.insightItemTitle}>Why This Time Window?</Text>
                <Text style={styles.insightItemText}>
                  Fraud occurred at 10:47 AM. Pattern analysis shows 89% of withdrawals happen within 30-60 min of last transfer. Predicted: 11:15-11:45 AM. Actual: 11:23 AM.
                </Text>
              </View>
            </View>
            
            <View style={styles.insightItemCard}>
              <Text style={styles.insightEmoji}>🔗</Text>
              <View style={styles.insightItemContent}>
                <Text style={styles.insightItemTitle}>Network Connection</Text>
                <Text style={styles.insightItemText}>
                  This mule network is connected to 12 previous cases. Same mastermind operating since Aug 2024. Total fraud: ₹47 lakhs.
                </Text>
              </View>
            </View>
            
            <View style={styles.insightItemCard}>
              <Text style={styles.insightEmoji}>🏦</Text>
              <View style={styles.insightItemContent}>
                <Text style={styles.insightItemTitle}>Cross-Bank Pattern</Text>
                <Text style={styles.insightItemText}>
                  Federated Learning detected this pattern: Rapid cascade ({'<'} 5 min between transfers) + Account age {'<'} 6 months = 94% fraud probability.
                </Text>
              </View>
            </View>
          </View>
        </LinearGradient>

        {/* Feature Importance - Matching MVP */}
        <View style={[styles.card, { backgroundColor: '#FFFFFF' }]}>
          <View style={styles.cardHeader}>
            <Ionicons name="analytics" size={24} color="#f59e0b" />
            <Text style={styles.cardTitle}>What Made the Prediction?</Text>
          </View>
          <Text style={styles.featureSubtitle}>Feature importance for location prediction</Text>
          
          <View style={styles.featureList}>
            <View style={styles.featureItem}>
              <View style={styles.featureHeader}>
                <Text style={styles.featureLabel}>Mule's Address Proximity</Text>
                <Text style={[styles.featureValue, { color: '#f59e0b' }]}>35%</Text>
              </View>
              <View style={styles.progressBar}>
                <View style={[styles.progressFill, { width: '35%', backgroundColor: '#f59e0b' }]} />
              </View>
            </View>
            
            <View style={styles.featureItem}>
              <View style={styles.featureHeader}>
                <Text style={styles.featureLabel}>Historical Patterns</Text>
                <Text style={[styles.featureValue, { color: '#f59e0b' }]}>28%</Text>
              </View>
              <View style={styles.progressBar}>
                <View style={[styles.progressFill, { width: '28%', backgroundColor: '#f59e0b' }]} />
              </View>
            </View>
            
            <View style={styles.featureItem}>
              <View style={styles.featureHeader}>
                <Text style={styles.featureLabel}>ATM Cash Availability</Text>
                <Text style={[styles.featureValue, { color: '#f97316' }]}>18%</Text>
              </View>
              <View style={styles.progressBar}>
                <View style={[styles.progressFill, { width: '18%', backgroundColor: '#f97316' }]} />
              </View>
            </View>
            
            <View style={styles.featureItem}>
              <View style={styles.featureHeader}>
                <Text style={styles.featureLabel}>Time of Day Pattern</Text>
                <Text style={[styles.featureValue, { color: '#f97316' }]}>12%</Text>
              </View>
              <View style={styles.progressBar}>
                <View style={[styles.progressFill, { width: '12%', backgroundColor: '#f97316' }]} />
              </View>
            </View>
            
            <View style={styles.featureItem}>
              <View style={styles.featureHeader}>
                <Text style={styles.featureLabel}>Network Behavior</Text>
                <Text style={[styles.featureValue, { color: '#eab308' }]}>7%</Text>
              </View>
              <View style={styles.progressBar}>
                <View style={[styles.progressFill, { width: '7%', backgroundColor: '#eab308' }]} />
              </View>
            </View>
          </View>
        </View>

        {/* Model Details - Matching MVP */}
        <View style={[styles.card, { backgroundColor: '#f3f4f6' }]}>
          <View style={styles.cardHeader}>
            <Ionicons name="code" size={20} color="#6b7280" />
            <Text style={[styles.cardTitle, { fontSize: 14, color: '#374151' }]}>Technical Details</Text>
          </View>
          <View style={styles.codeBlock}>
            <Text style={styles.codeText}>
              <Text style={styles.codeComment}>// Model Configuration{'\n'}</Text>
              model: "AEGIS-CST-Transformer-v2.1"{'\n'}
              training_data: "1.2M transactions"{'\n'}
              federated_banks: 12{'\n'}
              location_accuracy: 94.2%{'\n'}
              inference_time: 23.4ms{'\n'}
              <Text style={styles.codeComment}>// Confidence: HIGH (0.94)</Text>
            </Text>
          </View>
        </View>

        {/* Performance Metrics */}
        <View style={[styles.card, { backgroundColor: '#FFFFFF' }]}>
          <Text style={styles.cardTitle}>Performance Metrics</Text>
          <View style={styles.metricItem}>
            <Text style={styles.metricLabel}>Freeze Time</Text>
            <Text style={styles.metricValue}>47 seconds</Text>
          </View>
          <View style={styles.metricItem}>
            <Text style={styles.metricLabel}>Prediction Accuracy</Text>
            <Text style={styles.metricValue}>94% (Exact Match)</Text>
          </View>
          <View style={styles.metricItem}>
            <Text style={styles.metricLabel}>Recovery Rate</Text>
            <Text style={styles.metricValue}>88.6%</Text>
          </View>
          <View style={styles.metricItem}>
            <Text style={styles.metricLabel}>Total Response Time</Text>
            <Text style={styles.metricValue}>23 minutes</Text>
          </View>
        </View>
      </ScrollView>

      {/* Bottom Actions - Matching MVP exactly */}
      <View style={styles.bottomActions}>
        <View style={styles.bottomActionsRow}>
          <TouchableOpacity
            style={styles.exportButton}
            onPress={handleDownload}
            activeOpacity={0.8}
          >
            <LinearGradient
              colors={['#3b82f6', '#2563eb']}
              style={styles.exportGradient}
            >
              <Ionicons name="document" size={20} color="#FFFFFF" />
              <Text style={styles.exportButtonText}>Export PDF</Text>
            </LinearGradient>
          </TouchableOpacity>
          <TouchableOpacity
            style={styles.dashboardButton}
            onPress={() => {
              // @ts-ignore - React Navigation type inference limitation
              navigation.navigate('MainTabs' as never);
            }}
            activeOpacity={0.7}
          >
            <Ionicons name="home" size={20} color="#374151" />
            <Text style={styles.dashboardButtonText}>Dashboard</Text>
          </TouchableOpacity>
        </View>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  header: {
    paddingTop: 12,
    paddingBottom: 24,
    paddingHorizontal: 20,
  },
  headerContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 16,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerText: {
    flex: 1,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  headerSubtitle: {
    fontSize: 12,
    color: 'rgba(255, 255, 255, 0.7)',
  },
  iconButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  aiBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 12,
    padding: 12,
  },
  aiBadgeGradient: {
    width: 32,
    height: 32,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  aiBadgeTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  aiBadgeSubtitle: {
    fontSize: 12,
    color: 'rgba(255, 255, 255, 0.6)',
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    padding: 20,
    paddingBottom: 40,
  },
  card: {
    borderRadius: 16,
    padding: 20,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 16,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#111827',
  },
  statsGrid: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 16,
  },
  statBox: {
    flex: 1,
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
  },
  statValue: {
    fontSize: 24,
    fontWeight: '700',
    marginBottom: 4,
  },
  statLabel: {
    fontSize: 12,
    color: '#6b7280',
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#f3f4f6',
  },
  summaryLabel: {
    fontSize: 14,
    color: '#6b7280',
  },
  summaryValue: {
    fontSize: 14,
    fontWeight: '600',
    color: '#111827',
  },
  timeline: {
    marginTop: 8,
  },
  timelineItem: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 20,
  },
  timelineDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    marginTop: 4,
  },
  timelineContent: {
    flex: 1,
  },
  timelineTime: {
    fontSize: 12,
    fontWeight: '600',
    color: '#6b7280',
    marginBottom: 4,
  },
  timelineEvent: {
    fontSize: 14,
    color: '#111827',
  },
  insightBox: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    backgroundColor: '#f9fafb',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
  },
  insightText: {
    flex: 1,
    fontSize: 14,
    color: '#374151',
    lineHeight: 20,
  },
  metricItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#f3f4f6',
  },
  metricLabel: {
    fontSize: 14,
    color: '#6b7280',
  },
  metricValue: {
    fontSize: 14,
    fontWeight: '600',
    color: '#111827',
  },
  bottomActions: {
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: '#f3f4f6',
    padding: 16,
    paddingBottom: 32,
  },
  bottomActionsRow: {
    flexDirection: 'row',
    gap: 12,
  },
  exportButton: {
    flex: 1,
    borderRadius: 12,
    overflow: 'hidden',
  },
  exportGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
  },
  exportButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  dashboardButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    backgroundColor: '#f3f4f6',
    borderRadius: 12,
  },
  dashboardButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#374151',
  },
  successBanner: {
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
  },
  successBannerContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  successIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  successCheck: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '700',
  },
  successTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#166534',
    marginBottom: 4,
  },
  successSubtitle: {
    fontSize: 14,
    color: '#16a34a',
  },
  accuracyMetrics: {
    gap: 12,
  },
  accuracyMetric: {
    gap: 4,
  },
  accuracyHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  accuracyLabel: {
    fontSize: 14,
    color: '#6b7280',
  },
  accuracyValue: {
    fontSize: 14,
    fontWeight: '700',
  },
  progressBar: {
    height: 8,
    backgroundColor: '#f3f4f6',
    borderRadius: 4,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    borderRadius: 4,
  },
  aiTimeline: {
    position: 'relative',
    paddingLeft: 24,
    gap: 16,
  },
  timelineLine: {
    position: 'absolute',
    left: 8,
    top: 8,
    bottom: 8,
    width: 2,
    backgroundColor: '#e5e7eb',
  },
  aiStep: {
    position: 'relative',
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  aiStepDot: {
    position: 'absolute',
    left: -20,
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#FFFFFF',
    zIndex: 1,
  },
  aiStepCard: {
    flex: 1,
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
  },
  aiStepLabel: {
    fontSize: 12,
    fontWeight: '600',
    marginBottom: 4,
  },
  aiStepText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#374151',
    marginBottom: 8,
  },
  aiStepDetails: {
    gap: 4,
    marginBottom: 8,
  },
  aiStepDetailText: {
    fontSize: 12,
    color: '#6b7280',
  },
  aiStepTime: {
    fontSize: 12,
    color: '#9ca3af',
    fontFamily: 'monospace',
  },
  bankFlow: {
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    marginBottom: 8,
  },
  bankFlowText: {
    fontSize: 12,
    color: '#6b7280',
  },
  actionBadges: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 8,
  },
  actionBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  actionBadgeText: {
    fontSize: 12,
    fontWeight: '600',
  },
  insightsCard: {
    borderRadius: 16,
    padding: 16,
    marginBottom: 20,
  },
  insightsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 16,
  },
  insightsTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  insightItems: {
    gap: 12,
  },
  insightItemCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 12,
    padding: 12,
  },
  insightEmoji: {
    fontSize: 24,
  },
  insightItemContent: {
    flex: 1,
  },
  insightItemTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
    marginBottom: 4,
  },
  insightItemText: {
    fontSize: 12,
    color: '#d1d5db',
    lineHeight: 18,
  },
  featureSubtitle: {
    fontSize: 12,
    color: '#6b7280',
    marginBottom: 12,
  },
  featureList: {
    gap: 12,
  },
  featureItem: {
    gap: 4,
  },
  featureHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  featureLabel: {
    fontSize: 14,
    color: '#6b7280',
  },
  featureValue: {
    fontSize: 14,
    fontWeight: '700',
    fontFamily: 'monospace',
  },
  codeBlock: {
    backgroundColor: '#1e293b',
    borderRadius: 12,
    padding: 12,
  },
  codeText: {
    fontSize: 12,
    fontFamily: 'monospace',
    color: '#cbd5e1',
    lineHeight: 18,
  },
  codeComment: {
    color: '#4ade80',
  },
});

