import React, { useState, useRef, useEffect } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  Animated,
  Dimensions,
  Modal,
  SafeAreaView,
  ActivityIndicator,
  Alert,
} from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { Ionicons } from '@expo/vector-icons';
import { useRoute, useNavigation } from '@react-navigation/native';
import { useTheme } from '../theme/theme';
import { caseService } from '../api/caseService';
import { extractMuleAccountsFromTransactions } from '../utils/muleAccountUtils';
// Using View-based visualization for better compatibility

const { width: SCREEN_WIDTH } = Dimensions.get('window');
const GRAPH_WIDTH = SCREEN_WIDTH - 40;
const GRAPH_HEIGHT = 400;

interface NetworkNode {
  id: string;
  type: 'victim' | 'mule' | 'frozen' | 'unknown';
  name: string;
  bank: string;
  accountNumber: string;
  accountHolder: string;
  amount: number;
  status: 'active' | 'frozen' | 'withdrawn' | 'unused';
  x: number;
  y: number;
  label: string;
  muleNumber?: string;
  balance?: number;
  tooltip?: {
    title: string;
    details: string[];
  };
}

export default function MuleNetworkScreen() {
  const { theme } = useTheme();
  const route = useRoute();
  const navigation = useNavigation();
  const { caseId } = route.params as any || {};

  const [selectedNode, setSelectedNode] = useState<NetworkNode | null>(null);
  const [showTooltip, setShowTooltip] = useState(false);
  const [loading, setLoading] = useState(true);
  const [nodes, setNodes] = useState<NetworkNode[]>([]);
  const [cstPrediction, setCstPrediction] = useState<any>(null);
  const [frozenAccountIds, setFrozenAccountIds] = useState<Set<string>>(new Set());
  const pulseAnim = useRef(new Animated.Value(1)).current;

  useEffect(() => {
    loadNetworkData();
    loadCSTPrediction();
    
    // Pulse animation for predicted ATM
    Animated.loop(
      Animated.sequence([
        Animated.timing(pulseAnim, {
          toValue: 1.2,
          duration: 1000,
          useNativeDriver: true,
        }),
        Animated.timing(pulseAnim, {
          toValue: 1,
          duration: 1000,
          useNativeDriver: true,
        }),
      ])
    ).start();
  }, [caseId]);

  const loadCSTPrediction = async () => {
    try {
      const { predictionService } = await import('../api/predictionService');
      const result = await predictionService.getCasePrediction(caseId);
      if (result.success && result.data?.location_prediction?.primary) {
        setCstPrediction(result.data.location_prediction.primary);
      }
    } catch (error) {
      console.warn('Failed to load CST prediction:', error);
    }
  };

  const loadNetworkData = async () => {
    if (!caseId) {
      setLoading(false);
      return;
    }

    try {
      setLoading(true);
      
      // Get case details to get fraud amount
      const caseResponse = await caseService.getCaseDetails(caseId);
      const originalFraudAmount = caseResponse.success && caseResponse.data?.complaint?.fraud_amount 
        ? caseResponse.data.complaint.fraud_amount 
        : null;
      
      // Get transactions from CFCFRMS (generated by simulator)
      const transactionsResponse = await caseService.getCaseTransactions(caseId);
      
      if (transactionsResponse.success && transactionsResponse.data?.transactions) {
        const txns = transactionsResponse.data.transactions;
        
        // Transform transactions to network nodes
        const networkNodes = transformTransactionsToNetworkNodes(txns, originalFraudAmount);
        setNodes(networkNodes);
      } else {
        // No transactions found - show empty state
        console.log('No transactions found for case:', caseId);
        setNodes([]);
      }
    } catch (error) {
      console.error('Error loading network data:', error);
      setNodes([]);
    } finally {
      setLoading(false);
    }
  };

  const transformTransactionsToNetworkNodes = (
    transactions: any[],
    originalFraudAmount: number | null = null
  ): NetworkNode[] => {
    const networkNodes: NetworkNode[] = [];
    const processedAccounts = new Set<string>();
    const accountMap = new Map<string, any>();
    
    // Sort transactions by hop_number and timestamp
    const sortedTxns = [...transactions].sort((a, b) => {
      if (a.hop_number !== b.hop_number) return a.hop_number - b.hop_number;
      return new Date(a.transaction_timestamp || a.timestamp).getTime() - new Date(b.transaction_timestamp || b.timestamp).getTime();
    });
    
    // Find victim account from first transaction
    const firstTxn = sortedTxns.length > 0 ? sortedTxns[0] : null;
    const victimAccount = firstTxn?.from_account || '';
    
    // Add victim node
    if (firstTxn && originalFraudAmount) {
      networkNodes.push({
        id: 'victim',
        type: 'victim',
        name: firstTxn.from_holder_name || 'Victim',
        bank: firstTxn.from_bank || 'Unknown Bank',
        accountNumber: victimAccount ? `XXXX${victimAccount.slice(-4)}` : 'XXXX',
        accountHolder: firstTxn.from_holder_name || 'Victim',
        amount: originalFraudAmount,
        status: 'active',
        x: 160,
        y: 50,
        label: 'VICTIM',
        balance: originalFraudAmount,
        tooltip: {
          title: '● VICTIM',
          details: [
            `Name: ${firstTxn.from_holder_name || 'Victim'}`,
            `Bank: ${firstTxn.from_bank || 'Unknown Bank'}`,
            `A/C: ${victimAccount ? `XXXX${victimAccount.slice(-4)}` : 'XXXX'}`,
            `Lost: ₹${(originalFraudAmount / 100000).toFixed(1)}L`,
          ],
        },
      });
      processedAccounts.add(victimAccount);
    }
    
    // Process transactions to create mule account nodes
    let muleIndex = 1;
    const hopGroups = new Map<number, any[]>();
    
    // Group by hop number
    sortedTxns.forEach(txn => {
      const hop = txn.hop_number || 1;
      if (!hopGroups.has(hop)) {
        hopGroups.set(hop, []);
      }
      hopGroups.get(hop)!.push(txn);
    });
    
    // Process each hop
    const maxHop = Math.max(...Array.from(hopGroups.keys()));
    let yPosition = 160; // Start position for mules
    
    for (let hop = 1; hop <= maxHop; hop++) {
      const hopTxns = hopGroups.get(hop) || [];
      const uniqueAccounts = new Set<string>();
      
      // Collect unique accounts in this hop
      hopTxns.forEach(txn => {
        if (txn.to_account && !processedAccounts.has(txn.to_account)) {
          uniqueAccounts.add(txn.to_account);
        }
      });
      
      // Create nodes for unique accounts
      const accountsArray = Array.from(uniqueAccounts);
      const accountsPerRow = Math.min(accountsArray.length, 4);
      const availableWidth = Number(GRAPH_WIDTH) - 160;
      const spacingValue = accountsPerRow > 1 ? availableWidth / (accountsPerRow - 1) : 0;
      const startX = 80;
      
      accountsArray.forEach((accountId, idx) => {
        // Find transaction for this account
        const txn = hopTxns.find(t => t.to_account === accountId);
        if (!txn) return;
        
        const isFraudster = hop === 1; // First hop = fraudster
        const accountStatus = txn.status === 'FROZEN' ? 'frozen' : 
                             txn.status === 'WITHDRAWN' ? 'withdrawn' : 
                             frozenAccountIds.has(accountId) ? 'frozen' : 'active';
        
        const nodeType = accountStatus === 'frozen' ? 'frozen' : 
                        accountStatus === 'withdrawn' ? 'unknown' : 'mule';
        
        const muleLabel = isFraudster ? 'FRAUDSTER' : `M${muleIndex++}`;
        const accountName = isFraudster ? 'Fraudster' : 
                           txn.to_holder_name || `Mule ${muleIndex - 1}`;
        
        const balance = txn.to_balance_after !== undefined && txn.to_balance_after !== null
          ? txn.to_balance_after
          : txn.amount || 0;
        
        const location = txn.to_location 
          ? `${txn.to_location.city || ''}, ${txn.to_location.state || ''}`.trim()
          : 'Unknown';
        
        const nodeX = startX + (idx * spacingValue);
        
        networkNodes.push({
          id: accountId,
          type: nodeType,
          name: muleLabel,
          bank: txn.to_bank || 'Unknown',
          accountNumber: accountId ? `XXXX${accountId.slice(-4)}` : 'XXXX',
          accountHolder: accountName,
          amount: txn.amount || 0,
          status: accountStatus,
          x: nodeX,
          y: yPosition,
          label: muleLabel,
          muleNumber: muleLabel,
          balance: balance,
          tooltip: {
            title: accountStatus === 'frozen' ? '● FROZEN' : 
                  isFraudster ? '● FRAUDSTER • ACTIVE' : '● ACTIVE MULE',
            details: [
              `Name: ${accountName}`,
              `Bank: ${txn.to_bank || 'Unknown'}`,
              `A/C: ${accountId ? `XXXX${accountId.slice(-4)}` : 'XXXX'}`,
              accountStatus === 'frozen' 
                ? `Frozen Amt: ₹${(balance / 100000).toFixed(1)}L`
                : `Balance: ₹${(balance / 100000).toFixed(1)}L`,
              accountStatus === 'frozen' 
                ? '✓ Frozen'
                : '⚠ Flagged for freeze',
            ],
          },
        });
        
        processedAccounts.add(accountId);
        accountMap.set(accountId, { txn, balance, status: accountStatus });
      });
      
      // Move to next row
      if (uniqueAccounts.size > 0) {
        yPosition += 120;
      }
    }
    
    // Add predicted ATM node at the bottom
    if (networkNodes.length > 0 && cstPrediction) {
      const lastMule = networkNodes.filter(n => n.type === 'mule' && n.status === 'active').pop();
      if (lastMule) {
        networkNodes.push({
          id: 'atm',
          type: 'unknown',
          name: 'ATM',
          bank: cstPrediction.bank || 'ATM',
          accountNumber: cstPrediction.address || 'Predicted Location',
          accountHolder: '',
          amount: lastMule.balance || lastMule.amount,
          status: 'active',
          x: 60,
          y: yPosition + 80,
          label: 'ATM',
          tooltip: {
            title: '⚡ PREDICTED WITHDRAWAL',
            details: [
              cstPrediction.name || 'Predicted ATM',
              cstPrediction.address || 'Location',
              `Window: ${cstPrediction.time_window?.start ? new Date(cstPrediction.time_window.start).toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit' }) : 'Soon'} - ${cstPrediction.time_window?.end ? new Date(cstPrediction.time_window.end).toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit' }) : 'Soon'}`,
              `Confidence: ${Math.round((cstPrediction.confidence || 0.94) * 100)}%`,
            ],
          },
        });
      }
    }
    
    return networkNodes;
  };

  // Re-transform nodes when CST prediction loads
  useEffect(() => {
    if (cstPrediction && nodes.length > 0) {
      // Reload to include ATM node
      loadNetworkData();
    }
  }, [cstPrediction]);

  const formatCurrency = (amount: number) => {
    if (amount >= 100000) {
      return `₹${(amount / 100000).toFixed(1)}L`;
    }
    return `₹${amount.toLocaleString()}`;
  };

  const getNodeColor = (node: NetworkNode) => {
    if (node.type === 'victim') return '#22C55E';
    if (node.type === 'frozen') return '#EF4444';
    if (node.type === 'mule' && node.status === 'active') return '#F97316';
    return '#6B7280';
  };

  const handleNodePress = (node: NetworkNode) => {
    setSelectedNode(node);
    setShowTooltip(true);
  };

  const handleFreezeAll = () => {
    const activeMuleNodes = nodes.filter(
      (n) => n.type === 'mule' && n.status === 'active'
    );
    
    if (activeMuleNodes.length === 0) {
      Alert.alert('Info', 'No active accounts to freeze');
      return;
    }

    // Navigate to MuleAccountsScreen which handles the freeze workflow
    // @ts-ignore - React Navigation type inference limitation
    navigation.navigate('MuleAccounts' as never, {
      caseId,
      muleAccounts: activeMuleNodes.map((n) => ({
        id: n.id,
        bank: n.bank,
        bankName: n.bank,
        accountNumber: n.accountNumber,
        amountReceived: n.amount,
        currentBalance: n.balance || n.amount,
        accountHolder: n.accountHolder,
        ifscCode: 'XXXX0000000',
        accountAge: 'Unknown',
        location: n.tooltip?.details.find(d => d.includes('Location')) || 'Unknown',
        status: n.status,
      })),
    } as never);
  };

  // Calculate stats from nodes
  const activeNodes = React.useMemo(() => 
    nodes.filter((n) => n.type === 'mule' && n.status === 'active'),
    [nodes]
  );
  const totalNodes = nodes.length;
  const activeCount = activeNodes.length;
  const atRiskAmount = React.useMemo(() => 
    activeNodes.reduce((sum, n) => sum + (n.balance || n.amount || 0), 0),
    [activeNodes]
  );

  // Render network nodes dynamically
  const renderNetworkNodes = () => {
    if (loading) {
      return (
        <View style={styles.loadingContainer}>
          <ActivityIndicator size="large" color="#FFFFFF" />
          <Text style={styles.loadingText}>Loading network data...</Text>
        </View>
      );
    }

    if (nodes.length === 0) {
      return (
        <View style={styles.emptyState}>
          <Ionicons name="alert-circle-outline" size={48} color="#9ca3af" />
          <Text style={styles.emptyStateTitle}>No Network Data</Text>
          <Text style={styles.emptyStateText}>
            Network visualization will appear once CFCFRMS completes money flow tracing.
          </Text>
        </View>
      );
    }

    // Group nodes by y position (rows)
    const rows = new Map<number, NetworkNode[]>();
    nodes.forEach(node => {
      const y = node.y;
      if (!rows.has(y)) {
        rows.set(y, []);
      }
      rows.get(y)!.push(node);
    });

    const sortedRows = Array.from(rows.entries()).sort((a, b) => a[0] - b[0]);

    return (
      <View style={styles.graphCanvas}>
        {sortedRows.map(([yPos, rowNodes], rowIdx) => {
          // Victim row (centered)
          if (rowNodes[0]?.type === 'victim') {
            return (
              <View key={`row-${rowIdx}`} style={styles.nodeRow}>
                <View style={styles.spacer} />
                <TouchableOpacity
                  style={[styles.nodeCircle, { backgroundColor: '#22C55E' }]}
                  onPress={() => handleNodePress(rowNodes[0])}
                  activeOpacity={0.8}
                >
                  <Text style={styles.nodeLabel}>VICTIM</Text>
                  <Text style={styles.nodeSubLabel}>{rowNodes[0].name.slice(0, 8)}</Text>
                </TouchableOpacity>
                <View style={styles.spacer} />
              </View>
            );
          }

          // ATM row (centered, animated)
          if (rowNodes[0]?.id === 'atm') {
            return (
              <View key={`row-${rowIdx}`} style={styles.atmRow}>
                <Animated.View
                  style={[
                    styles.atmNode,
                    {
                      transform: [{ scale: pulseAnim }],
                    },
                  ]}
                >
                  <TouchableOpacity
                    style={[styles.nodeCircle, { backgroundColor: '#EF4444', width: 40, height: 40, borderRadius: 20 }]}
                    onPress={() => handleNodePress(rowNodes[0])}
                    activeOpacity={0.8}
                  >
                    <Text style={[styles.nodeLabel, { fontSize: 10 }]}>ATM</Text>
                  </TouchableOpacity>
                </Animated.View>
              </View>
            );
          }

          // Mule rows (distributed)
          return (
            <View key={`row-${rowIdx}`} style={styles.nodeRow}>
              {rowNodes.map((node, nodeIdx) => {
                const nodeColor = getNodeColor(node);
                const opacity = node.status === 'unused' ? 0.3 : node.status === 'frozen' ? 1 : 1;
                
                return (
                  <TouchableOpacity
                    key={node.id}
                    style={[styles.nodeCircle, { backgroundColor: nodeColor, opacity }]}
                    onPress={() => handleNodePress(node)}
                    activeOpacity={0.8}
                  >
                    <Text style={styles.nodeLabel}>{node.label}</Text>
                    <Text style={styles.nodeSubLabel}>{node.bank.slice(0, 6)}</Text>
                  </TouchableOpacity>
                );
              })}
            </View>
          );
        })}
      </View>
    );
  };

  return (
    <SafeAreaView style={[styles.container, { backgroundColor: '#0F172A' }]}>
      {/* Header */}
      <View style={styles.header}>
        <TouchableOpacity
          style={styles.backButton}
          onPress={() => navigation.goBack()}
          activeOpacity={0.7}
        >
          <Ionicons name="arrow-back" size={20} color="#FFFFFF" />
        </TouchableOpacity>
        <View style={styles.headerText}>
          <Text style={styles.headerTitle}>Mule Network</Text>
          <Text style={styles.headerSubtitle}>Case #{caseId || 'MH-2025-84721'}</Text>
        </View>
        <TouchableOpacity style={styles.filterButton} activeOpacity={0.7}>
          <Ionicons name="options" size={20} color="#FFFFFF" />
        </TouchableOpacity>
      </View>

      <ScrollView
        style={styles.scrollView}
        contentContainerStyle={styles.scrollContent}
        showsVerticalScrollIndicator={false}
      >
        {/* Network Visualization */}
        <View style={styles.graphContainer}>
          {renderNetworkNodes()}

          {/* Hover Instruction */}
          {!loading && nodes.length > 0 && (
            <View style={styles.hoverHint}>
              <Ionicons name="hand-left" size={12} color="#9CA3AF" />
              <Text style={styles.hoverText}>Tap nodes for details</Text>
            </View>
          )}
        </View>

        {/* Legend */}
        <View style={styles.legend}>
          <Text style={styles.legendTitle}>LEGEND</Text>
          <View style={styles.legendGrid}>
            <View style={styles.legendItem}>
              <View style={[styles.legendDot, { backgroundColor: '#22C55E' }]} />
              <Text style={styles.legendText}>Victim</Text>
            </View>
            <View style={styles.legendItem}>
              <View style={[styles.legendDot, { backgroundColor: '#F97316' }]} />
              <Text style={styles.legendText}>Active Mule</Text>
            </View>
            <View style={styles.legendItem}>
              <View style={[styles.legendDot, { backgroundColor: '#EF4444' }]} />
              <Text style={styles.legendText}>Frozen</Text>
            </View>
            <View style={styles.legendItem}>
              <View style={[styles.legendDot, { backgroundColor: '#6B7280', opacity: 0.5 }]} />
              <Text style={styles.legendText}>Unused/Unknown</Text>
            </View>
          </View>
        </View>

        {/* Network Stats */}
        {!loading && nodes.length > 0 && (
          <View style={styles.statsGrid}>
            <View style={styles.statCard}>
              <Text style={styles.statValue}>{totalNodes}</Text>
              <Text style={styles.statLabel}>Nodes</Text>
            </View>
            <View style={styles.statCard}>
              <Text style={styles.statValue}>{activeCount}</Text>
              <Text style={styles.statLabel}>Active</Text>
            </View>
            <View style={styles.statCard}>
              <Text style={[styles.statValue, { color: '#F97316' }]}>
                {formatCurrency(atRiskAmount)}
              </Text>
              <Text style={styles.statLabel}>At Risk</Text>
            </View>
          </View>
        )}
      </ScrollView>

      {/* Bottom Actions */}
      {!loading && activeCount > 0 && (
        <View style={styles.bottomActions}>
          <TouchableOpacity
            style={styles.freezeButton}
            onPress={handleFreezeAll}
            activeOpacity={0.8}
          >
            <LinearGradient
              colors={['#EF4444', '#DC2626']}
              style={styles.freezeButtonGradient}
            >
              <Ionicons name="ban" size={20} color="#FFFFFF" />
              <Text style={styles.freezeButtonText}>
                Freeze All Active Nodes ({activeCount})
              </Text>
            </LinearGradient>
          </TouchableOpacity>
        </View>
      )}

      {/* Node Details Modal */}
      <Modal
        visible={showTooltip && selectedNode !== null}
        transparent
        animationType="fade"
        onRequestClose={() => {
          setShowTooltip(false);
          setSelectedNode(null);
        }}
      >
        <TouchableOpacity
          style={styles.modalOverlay}
          activeOpacity={1}
          onPress={() => {
            setShowTooltip(false);
            setSelectedNode(null);
          }}
        >
          {selectedNode && selectedNode.tooltip && (
            <View style={styles.tooltip}>
              <Text style={[styles.tooltipTitle, { color: getNodeColor(selectedNode) }]}>
                {selectedNode.tooltip.title}
              </Text>
              {selectedNode.tooltip.details.map((detail, index) => (
                <Text key={index} style={styles.tooltipDetail}>
                  {detail}
                </Text>
              ))}
            </View>
          )}
        </TouchableOpacity>
      </Modal>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 16,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerText: {
    flex: 1,
    marginLeft: 12,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  headerSubtitle: {
    fontSize: 12,
    color: '#9CA3AF',
    marginTop: 2,
  },
  filterButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 100,
  },
  graphContainer: {
    height: 400,
    marginBottom: 16,
    position: 'relative',
    backgroundColor: 'rgba(255, 255, 255, 0.02)',
    borderRadius: 12,
    overflow: 'hidden',
  },
  graphCanvas: {
    width: '100%',
    height: '100%',
    justifyContent: 'space-between',
    paddingVertical: 20,
  },
  nodeRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  spacer: {
    flex: 1,
  },
  nodeCircle: {
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  nodeLabel: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '600',
  },
  nodeSubLabel: {
    color: '#FFFFFF',
    fontSize: 8,
    marginTop: 2,
  },
  atmRow: {
    alignItems: 'center',
    marginTop: 20,
  },
  atmNode: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  hoverHint: {
    position: 'absolute',
    top: 8,
    right: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  hoverText: {
    fontSize: 10,
    color: '#9CA3AF',
  },
  legend: {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
  },
  legendTitle: {
    fontSize: 12,
    fontWeight: '600',
    color: '#9CA3AF',
    marginBottom: 12,
  },
  legendGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  legendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    width: '48%',
  },
  legendDot: {
    width: 16,
    height: 16,
    borderRadius: 8,
  },
  legendText: {
    fontSize: 12,
    color: '#D1D5DB',
  },
  statsGrid: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 16,
  },
  statCard: {
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 12,
    padding: 12,
    alignItems: 'center',
  },
  statValue: {
    fontSize: 18,
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: 4,
  },
  statLabel: {
    fontSize: 12,
    color: '#9CA3AF',
  },
  bottomActions: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(15, 23, 42, 0.8)',
    padding: 16,
    paddingBottom: 32,
  },
  freezeButton: {
    borderRadius: 12,
    overflow: 'hidden',
  },
  freezeButtonGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    gap: 8,
  },
  freezeButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  tooltip: {
    backgroundColor: '#1E293B',
    borderRadius: 8,
    padding: 16,
    minWidth: 200,
    borderWidth: 1,
    borderColor: '#334155',
  },
  tooltipTitle: {
    fontSize: 11,
    fontWeight: '700',
    marginBottom: 8,
  },
  tooltipDetail: {
    fontSize: 10,
    color: '#CBD5E1',
    marginBottom: 4,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 60,
  },
  loadingText: {
    color: '#9CA3AF',
    fontSize: 14,
    marginTop: 12,
  },
  emptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 60,
    paddingHorizontal: 20,
  },
  emptyStateTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#FFFFFF',
    marginTop: 16,
    marginBottom: 8,
  },
  emptyStateText: {
    fontSize: 14,
    color: '#9CA3AF',
    textAlign: 'center',
    lineHeight: 20,
  },
});
